management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus,metrics

  endpoint:
    health:
      show-details: always


  metrics:
    distribution:
      percentiles.all: 0.5
      percentiles.http: 0.8,0.99


spring.datasource:
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: changeme

